# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_server_rust:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      env:
        workdir: ./server-rust 
      

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    # uses rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test
        run: cargo test
        working-directory: ${{env.workdir}}
